//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace meivorts.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class meivortsEntities : DbContext
    {
        public meivortsEntities()
            : base("name=meivortsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Compromisso> Compromissoes { get; set; }
        public virtual DbSet<Contato> Contatoes { get; set; }
        public virtual DbSet<TipoCompromisso> TipoCompromissoes { get; set; }
        public virtual DbSet<TipoContato> TipoContatoes { get; set; }
    }
}
