//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace meivorts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compromisso
    {
        public int ID { get; set; }
        public int IDLocal { get; set; }
        public string Descricao { get; set; }
        public System.DateTime Data { get; set; }
        public System.TimeSpan Hora { get; set; }
        public int TipoCompromisso { get; set; }
        public Nullable<int> Contato { get; set; }
        public int StatusCompromisso { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public System.DateTime DataAlteracao { get; set; }
        public bool Excluido { get; set; }
    
        public virtual Contato Contato1 { get; set; }
        public virtual Local Local { get; set; }
        public virtual StatusCompromisso StatusCompromisso1 { get; set; }
        public virtual TipoCompromisso TipoCompromisso1 { get; set; }
    }
}
