//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace guilhermecoelho.org.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTipoAgenda
    {
        public int id { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataGravacao { get; set; }
        public System.DateTime DataAlteracao { get; set; }
        public bool Excluido { get; set; }
    }
}
